import { PromptConfig } from './types';

export const PROMPT_CONFIG: PromptConfig = {
  species: [
    { value: "Original", label: "Original", prompt: "" },
    // D&D / Fantasy Common
    { value: "Human", label: "Human", prompt: "Transform the character into a Human. Add characteristic features of a Human while maintaining the original pose and identity." },
    { value: "Elf", label: "Elf", prompt: "Transform the character into an Elf. Add characteristic features of an Elf (pointed ears, elegant features) while maintaining the original pose and identity." },
    { value: "Half-Elf", label: "Half-Elf", prompt: "Transform the character into a Half-Elf. Add subtle elven features while maintaining the original pose and identity." },
    { value: "Drow", label: "Drow (Dark Elf)", prompt: "Transform the character into a Drow. Give them dark skin, white hair, and distinct elven features." },
    { value: "Dwarf", label: "Dwarf", prompt: "Transform the character into a Dwarf. Add characteristic features of a Dwarf (stout build, beard if male) while maintaining the original pose and identity." },
    { value: "Halfling", label: "Halfling", prompt: "Transform the character into a Halfling. Add characteristic features of a Halfling while maintaining the original pose and identity." },
    { value: "Gnome", label: "Gnome", prompt: "Transform the character into a Gnome. Add characteristic features of a Gnome while maintaining the original pose and identity." },
    { value: "Tiefling", label: "Tiefling", prompt: "Transform the character into a Tiefling. Add horns, a tail, and possibly unusual skin color." },
    { value: "Dragonborn", label: "Dragonborn", prompt: "Transform the character into a Dragonborn. Give them draconic scales and a dragon-like head." },
    { value: "Orc", label: "Orc", prompt: "Transform the character into an Orc. Give them green/grey skin, tusks, and a muscular build." },
    { value: "Half-Orc", label: "Half-Orc", prompt: "Transform the character into a Half-Orc. Give them prominent lower teeth, greyish skin, and a strong build." },
    { value: "Goblin", label: "Goblin", prompt: "Transform the character into a Goblin. Give them green skin, a large nose, and pointy ears." },
    { value: "Hobgoblin", label: "Hobgoblin", prompt: "Transform the character into a Hobgoblin. Give them orange/red skin and a disciplined, martial appearance." },
    { value: "Kobold", label: "Kobold", prompt: "Transform the character into a Kobold. Give them reptilian features, scales, and a small, wiry frame." },
    { value: "Genasi-Fire", label: "Genasi (Fire)", prompt: "Transform the character into a Fire Genasi. Give them burning red/orange skin and hair that resembles flames." },
    { value: "Genasi-Water", label: "Genasi (Water)", prompt: "Transform the character into a Water Genasi. Give them blue/green skin and a fluid, aquatic appearance." },
    { value: "Genasi-Air", label: "Genasi (Air)", prompt: "Transform the character into an Air Genasi. Give them pale blue skin and hair that seems to float." },
    { value: "Genasi-Earth", label: "Genasi (Earth)", prompt: "Transform the character into an Earth Genasi. Give them stone-like skin texture and earthy tones." },
    { value: "Aasimar", label: "Aasimar", prompt: "Transform the character into an Aasimar. Give them a divine, metallic sheen to their skin or eyes and an angelic presence." },
    { value: "Tabaxi", label: "Tabaxi", prompt: "Transform the character into a Tabaxi. Give them feline features, fur, and a cat-like tail." },
    { value: "Triton", label: "Triton", prompt: "Transform the character into a Triton. Give them aquatic features, webbed fingers, and fins." },
    { value: "Lizardfolk", label: "Lizardfolk", prompt: "Transform the character into Lizardfolk. Give them reptilian scales, a tail, and a lizard head." },
    { value: "Kenku", label: "Kenku", prompt: "Transform the character into a Kenku. Give them bird-like features, feathers, and a beak (flightless)." },
    { value: "Aarakocra", label: "Aarakocra", prompt: "Transform the character into an Aarakocra. Give them full bird features, wings, and talons." },
    { value: "Changeling", label: "Changeling", prompt: "Transform the character into a Changeling. Give them very pale, featureless skin and large dark eyes." },
    { value: "Warforged", label: "Warforged", prompt: "Transform the character into a Warforged. Give them a body made of wood, stone, and metal, appearing as a living construct." },
    { value: "Centaur", label: "Centaur", prompt: "Transform the character into a Centaur. Keep the human upper body but replace the lower body with that of a horse." },
    { value: "Loxodon", label: "Loxodon", prompt: "Transform the character into a Loxodon. Give them elephantine features, including a trunk and leathery skin." },
    { value: "Minotaur", label: "Minotaur", prompt: "Transform the character into a Minotaur. Give them a bull's head, horns, and a powerful, furry build." },
    { value: "Satyr", label: "Satyr", prompt: "Transform the character into a Satyr. Give them goat legs, hooves, and small horns." },
    // Star Trek / Sci-Fi
    { value: "Vulcan", label: "Vulcan", prompt: "Transform the character into a Vulcan. Add characteristic pointed ears and straight eyebrows." },
    { value: "Klingon", label: "Klingon", prompt: "Transform the character into a Klingon. Add characteristic ridges on the forehead and wild, voluminous hair." },
    { value: "Romulan", label: "Romulan", prompt: "Transform the character into a Romulan. Add pointed ears and a V-shaped forehead ridge." },
    { value: "Andorian", label: "Andorian", prompt: "Transform the character into an Andorian. Give them blue skin, white hair, and two antennae." },
    { value: "Borg", label: "Borg", prompt: "Transform the character into a Borg Drone. Add cybernetic implants, pale skin, and a mechanical eyepiece." },
    { value: "Cardassian", label: "Cardassian", prompt: "Transform the character into a Cardassian. Give them grey skin with distinct neck ridges and spoon-shaped forehead markings." },
    { value: "Ferengi", label: "Ferengi", prompt: "Transform the character into a Ferengi. Give them extremely large ears, sharp teeth, and a wrinkled nose." },
    { value: "Bajoran", label: "Bajoran", prompt: "Transform the character into a Bajoran. Add a crinkled ridge across the bridge of the nose." },
    { value: "Trill", label: "Trill", prompt: "Transform the character into a Trill. Add a pattern of dark spots running down the sides of their face and neck." },
    { value: "Orion", label: "Orion", prompt: "Transform the character into an Orion. Give them vibrant green skin." },
    { value: "Gorn", label: "Gorn", prompt: "Transform the character into a Gorn. Give them a full reptilian humanoid appearance with green scales and compound eyes." },
    // Other / Mythology
    { value: "Mermaid", label: "Mermaid", prompt: "Transform the character into a Mermaid. Replace legs with a fish tail and add aquatic features." },
    { value: "Angel", label: "Angel", prompt: "Transform the character into an Angel. Add large feathered wings, a halo, and a divine aura." },
    { value: "Demon", label: "Demon", prompt: "Transform the character into a Demon. Add horns, leathery wings, red skin, and a sinister aura." },
    { value: "Vampire", label: "Vampire", prompt: "Transform the character into a Vampire. Give them pale skin, fangs, and a gothic, aristocratic demeanor." },
    { value: "Werewolf", label: "Werewolf", prompt: "Transform the character into a Werewolf (hybrid form). Give them fur, a wolf-like snout, and claws." },
    { value: "Fairy", label: "Fairy", prompt: "Transform the character into a Fairy. Add insect-like wings (butterfly or dragonfly) and a magical glow." },
    { value: "Cyborg", label: "Cyborg", prompt: "Transform the character into a Cyborg. Integrate mechanical parts, metal plating, and glowing lights into their body." },
    { value: "Zombie", label: "Zombie", prompt: "Transform the character into a Zombie. Give them decaying skin, sunken eyes, and a tattered appearance." },
    { value: "Skeleton", label: "Skeleton", prompt: "Transform the character into a Skeleton. Remove all flesh, leaving only clean bone structure, perhaps wearing the original clothes." }
  ],
  genders: [
     { value: "Original", label: "Original", prompt: "" },
     { value: "Female", label: "Female", prompt: "Transform the character to appear Female. Adjust physical features to be typically feminine while preserving the character's identity." },
     { value: "Male", label: "Male", prompt: "Transform the character to appear Male. Adjust physical features to be typically masculine while preserving the character's identity." },
     { value: "Intersex", label: "Intersex", prompt: "Transform the character to appear Androgynous/Intersex. Blend masculine and feminine features for a non-binary appearance." }
  ],
  hairColors: [
    { value: "Original", label: "Original", prompt: "" },
    { value: "Blonde", label: "Blonde", prompt: "Change the character's hair color to Blonde. Keep the style and texture natural." },
    { value: "Black", label: "Black", prompt: "Change the character's hair color to Black. Keep the style and texture natural." },
    { value: "Brown", label: "Brown", prompt: "Change the character's hair color to Brown. Keep the style and texture natural." },
    { value: "Red", label: "Red / Ginger", prompt: "Change the character's hair color to Red / Ginger. Keep the style and texture natural." },
    { value: "Auburn", label: "Auburn", prompt: "Change the character's hair color to Auburn. Keep the style and texture natural." },
    { value: "White", label: "White", prompt: "Change the character's hair color to White. Keep the style and texture natural." },
    { value: "Grey", label: "Grey", prompt: "Change the character's hair color to Grey. Keep the style and texture natural." },
    { value: "Silver", label: "Silver", prompt: "Change the character's hair color to metallic Silver. Keep the style and texture natural." },
    { value: "Gold", label: "Gold", prompt: "Change the character's hair color to metallic Gold. Keep the style and texture natural." },
    { value: "Blue", label: "Blue", prompt: "Change the character's hair color to Blue. Keep the style and texture natural." },
    { value: "Green", label: "Green", prompt: "Change the character's hair color to Green. Keep the style and texture natural." },
    { value: "Pink", label: "Pink", prompt: "Change the character's hair color to Pink. Keep the style and texture natural." },
    { value: "Purple", label: "Purple", prompt: "Change the character's hair color to Purple. Keep the style and texture natural." },
    { value: "Orange", label: "Orange", prompt: "Change the character's hair color to Orange. Keep the style and texture natural." },
    { value: "Teal", label: "Teal", prompt: "Change the character's hair color to Teal. Keep the style and texture natural." },
    { value: "Multicolor", label: "Rainbow / Multicolor", prompt: "Change the character's hair color to Rainbow/Multicolor. Keep the style and texture natural." },
    { value: "Bald", label: "Bald", prompt: "Remove the character's hair completely. Render a realistic bald head." }
  ],
  skinTones: [
    { value: "Original", label: "Original", prompt: "" },
    { value: "Pale", label: "Pale / Porcelain", prompt: "Change the character's skin tone to Pale / Porcelain. Maintain realistic skin texture and lighting." },
    { value: "Fair", label: "Fair", prompt: "Change the character's skin tone to Fair. Maintain realistic skin texture and lighting." },
    { value: "Medium", label: "Medium / Beige", prompt: "Change the character's skin tone to Medium / Beige. Maintain realistic skin texture and lighting." },
    { value: "Olive", label: "Olive", prompt: "Change the character's skin tone to Olive. Maintain realistic skin texture and lighting." },
    { value: "Tan", label: "Tan / Bronze", prompt: "Change the character's skin tone to Tan / Bronze. Maintain realistic skin texture and lighting." },
    { value: "Brown", label: "Brown", prompt: "Change the character's skin tone to Brown. Maintain realistic skin texture and lighting." },
    { value: "DarkBrown", label: "Dark Brown", prompt: "Change the character's skin tone to Dark Brown. Maintain realistic skin texture and lighting." },
    { value: "Black", label: "Deep Black", prompt: "Change the character's skin tone to Deep Black. Maintain realistic skin texture and lighting." },
    { value: "Asian", label: "East Asian", prompt: "Change the character's features and skin tone to reflect East Asian ethnicity." },
    { value: "SouthAsian", label: "South Asian", prompt: "Change the character's features and skin tone to reflect South Asian ethnicity." },
    { value: "Hispanic", label: "Hispanic / Latino", prompt: "Change the character's features and skin tone to reflect Hispanic / Latino ethnicity." },
    { value: "MiddleEastern", label: "Middle Eastern", prompt: "Change the character's features and skin tone to reflect Middle Eastern ethnicity." },
    { value: "Indigenous", label: "Indigenous / Native American", prompt: "Change the character's features and skin tone to reflect Indigenous / Native American ethnicity." },
    // Fantasy
    { value: "Blue", label: "Fantasy Blue", prompt: "Change the character's skin tone to Blue (Alien). Maintain realistic skin texture." },
    { value: "Green", label: "Fantasy Green", prompt: "Change the character's skin tone to Green (Alien). Maintain realistic skin texture." },
    { value: "Red", label: "Fantasy Red", prompt: "Change the character's skin tone to Red (Alien). Maintain realistic skin texture." },
    { value: "Metallic", label: "Metallic / Robot", prompt: "Change the character's skin to appear Metallic or Robotic." },
  ],
  timeOfDay: [
    { value: "Original", label: "Original", prompt: "" },
    { value: "Sunrise", label: "Sunrise", prompt: "Change the lighting and atmosphere to depict Sunrise. Use soft, warm, low-angle light." },
    { value: "Morning", label: "Morning", prompt: "Change the lighting and atmosphere to depict a bright, clear Morning." },
    { value: "Noon", label: "Noon", prompt: "Change the lighting and atmosphere to depict High Noon. Use bright, direct, overhead sunlight." },
    { value: "Afternoon", label: "Afternoon", prompt: "Change the lighting and atmosphere to depict Afternoon." },
    { value: "GoldenHour", label: "Golden Hour", prompt: "Change the lighting and atmosphere to Golden Hour. Use warm, golden, directional light." },
    { value: "Sunset", label: "Sunset", prompt: "Change the lighting and atmosphere to depict Sunset. Use vibrant oranges, purples, and dramatic shadows." },
    { value: "BlueHour", label: "Blue Hour / Twilight", prompt: "Change the lighting and atmosphere to Blue Hour. Use cool, soft, ambient light just after sunset." },
    { value: "Evening", label: "Evening", prompt: "Change the lighting and atmosphere to Evening." },
    { value: "Night", label: "Night", prompt: "Change the lighting and atmosphere to Night. Use dark tones and moonlit highlights." },
    { value: "Midnight", label: "Midnight", prompt: "Change the lighting and atmosphere to Midnight. Use deep blacks and silvery moonlight." }
  ],
  techLevels: [
    { value: "Original", label: "Original", prompt: "" },
    { value: "Primitive", label: "Primitive", prompt: "Transform the setting and artifacts to a primitive, stone-age level. Use natural materials like stone, wood, and bone. Characters should wear furs or simple skins." },
    { value: "Ancient", label: "Ancient", prompt: "Transform the setting to an Ancient era (like Rome, Greece, or Egypt). Use classical architecture, sandals, tunics, and bronze/iron age technology." },
    { value: "Medieval", label: "Medieval", prompt: "Transform the setting to the Medieval period. Use castles, stone masonry, plate or leather armor, swords, and rustic clothing." },
    { value: "Renaissance", label: "Renaissance", prompt: "Transform the setting to the Renaissance period. Focus on ornate clothing, artistic flourishes, early firearms, and classical revival architecture." },
    { value: "Industrial", label: "Industrial", prompt: "Transform the setting to the Early Industrial/Steampunk era. Use steam power, gears, brass, brick factories, and Victorian-style clothing." },
    { value: "Modern", label: "Modern", prompt: "Transform the setting to the Modern day. Use contemporary fashion, smartphones, cars, and modern architecture." },
    { value: "Cyberpunk", label: "Cyberpunk", prompt: "Transform the setting to a Cyberpunk Near Future. Use neon lights, high-tech implants, holograms, dirty high-tech aesthetic, and synthetic materials." },
    { value: "Sci-Fi", label: "Sci-Fi", prompt: "Transform the setting to a clean Sci-Fi Future. Use spaceships, lasers, smooth white surfaces, advanced robotics, and tight-fitting functional suits." },
    { value: "Far Future", label: "Far Future", prompt: "Transform the setting to the Far Future. Use unrecognizable advanced technology, energy beings, organic-tech hybrids, and surreal landscapes." }
  ],
  ageGroups: [
    { value: "Original", label: "Original", prompt: "" },
    { value: "Preteen", label: "Preteen", prompt: "Modify the character's apparent age to be a Preteen. Adjust facial features, skin texture, and body proportions to reflect a Preteen individual while keeping the original identity recognizable." },
    { value: "Teenager", label: "Teenager", prompt: "Modify the character's apparent age to be a Teenager. Adjust facial features, skin texture, and body proportions to reflect a Teenager while keeping the original identity recognizable." },
    { value: "Young Adult", label: "Young Adult", prompt: "Modify the character's apparent age to be a Young Adult. Adjust facial features, skin texture, and body proportions to reflect a Young Adult while keeping the original identity recognizable." },
    { value: "Adult", label: "Adult", prompt: "Modify the character's apparent age to be an Adult. Adjust facial features, skin texture, and body proportions to reflect an Adult while keeping the original identity recognizable." },
    { value: "Middle-Aged", label: "Middle-Aged", prompt: "Modify the character's apparent age to be Middle-Aged. Adjust facial features, skin texture, and body proportions to reflect a Middle-Aged individual while keeping the original identity recognizable." },
    { value: "Elderly", label: "Elderly", prompt: "Modify the character's apparent age to be Elderly. Adjust facial features, skin texture, and body proportions to reflect an Elderly individual while keeping the original identity recognizable." }
  ],
  footwear: [
    { value: "Original", label: "Original", prompt: "" },
    { value: "Barefoot", label: "Barefoot", prompt: "Ensure the character is completely barefoot. Do not draw shoes, socks, or foot coverings." },
    { value: "Sandals", label: "Sandals", prompt: "Ensure the character is wearing Sandals." },
    { value: "Anklets", label: "Anklets", prompt: "Ensure the character is barefoot but wearing decorative anklets." },
    { value: "Clogs", label: "Clogs", prompt: "Ensure the character is wearing Clogs." },
    { value: "Sneakers", label: "Sneakers", prompt: "Ensure the character is wearing Sneakers." },
    { value: "Boots", label: "Boots", prompt: "Ensure the character is wearing Boots." },
    { value: "Shoes", label: "Shoes", prompt: "Ensure the character is wearing Shoes." },
    { value: "Leather Wraps", label: "Leather Wraps", prompt: "Ensure the character is wearing Leather Wraps on their feet." }
  ],
  backgrounds: [
    { value: "Original", label: "Original", prompt: "" },
    { value: "Transparent", label: "Transparent", prompt: "Remove the existing background completely and replace it with a transparent alpha channel. Ensure the output is a RGBA PNG with transparency." },
    // Nature
    { value: "Beach", label: "Beach", prompt: "Replace the background with a realistic Beach. Ensure lighting and reflections match." },
    { value: "Forest", label: "Forest", prompt: "Replace the background with a realistic Forest. Ensure lighting and shadows match." },
    { value: "Plains", label: "Plains", prompt: "Replace the background with realistic Plains. Ensure lighting and shadows match." },
    { value: "Snow", label: "Snow", prompt: "Replace the background with a Snowy landscape. Ensure lighting and shadows match." },
    { value: "Desert", label: "Desert", prompt: "Replace the background with a realistic Desert. Ensure lighting and shadows match." },
    { value: "Sea", label: "Sea", prompt: "Replace the background with the Sea. Ensure lighting and reflections match." },
    { value: "Rivers", label: "Rivers", prompt: "Replace the background with a River. Ensure lighting and reflections match." },
    { value: "Jungle", label: "Jungle", prompt: "Replace the background with a dense Jungle." },
    { value: "Mountains", label: "Mountains", prompt: "Replace the background with majestic Mountains." },
    { value: "Volcanic", label: "Volcanic Crater", prompt: "Replace the background with a Volcanic Crater, featuring lava and dark rock." },
    { value: "Ice Cave", label: "Ice Cave", prompt: "Replace the background with an Ice Cave, featuring blue translucent ice and cold lighting." },
    { value: "BioForest", label: "Bioluminescent Forest", prompt: "Replace the background with a Bioluminescent Forest, with glowing plants and night-time lighting." },
    // Cultural / Historical
    { value: "Dojo", label: "Japanese Dojo", prompt: "Replace the background with a traditional Japanese Dojo, with tatami mats and wooden architecture." },
    { value: "Aztec", label: "Aztec Temple", prompt: "Replace the background with an Aztec Temple, featuring stone pyramids and jungle overgrowth." },
    { value: "Gothic", label: "Gothic Cathedral", prompt: "Replace the background with a Gothic Cathedral, featuring stained glass, stone arches, and candles." },
    { value: "Victorian", label: "Victorian Street", prompt: "Replace the background with a foggy Victorian Street, featuring cobblestones and gas lamps." },
    { value: "Egypt", label: "Egyptian Pyramids", prompt: "Replace the background with Ancient Egyptian Pyramids and desert sands." },
    { value: "Roman", label: "Roman Forum", prompt: "Replace the background with the Roman Forum, featuring marble columns and classical statues." },
    { value: "Viking", label: "Viking Longhall", prompt: "Replace the background with a Viking Longhall, featuring wooden beams, fire pits, and shields." },
    { value: "Saloon", label: "Wild West Saloon", prompt: "Replace the background with a Wild West Saloon, featuring wooden floors and swinging doors." },
    { value: "Diner", label: "1950s Diner", prompt: "Replace the background with a 1950s Diner, featuring neon signs, checkerboard floors, and chrome." },
    { value: "Arabian", label: "Arabian Palace", prompt: "Replace the background with an Arabian Palace, featuring mosaics, arches, and silk curtains." },
    { value: "Chinese", label: "Chinese Garden", prompt: "Replace the background with a Chinese Garden, featuring pagodas, ponds, and cherry blossoms." },
    { value: "Greek", label: "Greek Acropolis", prompt: "Replace the background with the Greek Acropolis, featuring white marble temples under a blue sky." },
    // Sci-Fi / Modern
    { value: "City", label: "City", prompt: "Replace the background with a modern City." },
    { value: "Village", label: "Village", prompt: "Replace the background with a Village." },
    { value: "Spaceship", label: "Spaceship", prompt: "Replace the background with a Spaceship interior." },
    { value: "Moon", label: "Moon", prompt: "Replace the background with the Moon surface." },
    { value: "Mars", label: "Mars", prompt: "Replace the background with the surface of Mars." },
    { value: "SteampunkCity", label: "Steampunk City", prompt: "Replace the background with a Steampunk City, filled with brass gears, steam, and brick." },
    { value: "CyberpunkSlums", label: "Cyberpunk Slums", prompt: "Replace the background with Cyberpunk Slums, featuring neon signs, rain, and high-tech decay." },
    { value: "UnderwaterCity", label: "Underwater City", prompt: "Replace the background with an Underwater City, protected by a glass dome." },
    { value: "SkyCastle", label: "Sky Castle", prompt: "Replace the background with a Castle floating in the sky among clouds." },
    { value: "Castle", label: "Castle", prompt: "Replace the background with a Castle." },
    { value: "Library", label: "Library", prompt: "Replace the background with a Library." },
    { value: "Laboratory", label: "Laboratory", prompt: "Replace the background with a Laboratory." }
  ],
  clothing: [
    { value: "as-is", label: "As Is (Default)", prompt: "" },
    { value: "more", label: "More Clothing", prompt: "Add more layers of clothing. Ensure the character is well-covered and dressed warmly, adding coats, robes, or full outfits where appropriate." },
    { value: "less", label: "Fewer Clothes", prompt: "Reduce the amount of clothing to be lighter, such as summer wear, swimwear or lighter fabrics, suitable for a tropical environment. Do not generate explicit pornography, but artistic skin exposure is allowed if it fits the context." },
    { value: "nude", label: "Nude (Implied)", prompt: "Minimize clothing to the absolute limit. Use artistic framing, shadows, or barely-there coverings to imply nudity without explicit genitalia. Focus on the natural beauty of the anatomy and skin texture." }
  ]
};