
import { PromptConfig } from './types';

// Helper to sort options alphabetically by label
const sortOpts = (opts: any[]) => opts.sort((a, b) => a.label.localeCompare(b.label));

export const PROMPT_CONFIG: PromptConfig = {
  species: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Aarakocra", label: "Aarakocra", prompt: "Transform the character into an Aarakocra. Give them full bird features, wings, and talons." },
    { value: "Aasimar", label: "Aasimar", prompt: "Transform the character into an Aasimar. Give them a divine, metallic sheen to their skin or eyes and an angelic presence." },
    { value: "Andorian", label: "Andorian", prompt: "Transform the character into an Andorian. Give them blue skin, white hair, and two antennae." },
    { value: "Angel", label: "Angel", prompt: "Transform the character into an Angel. Add large feathered wings, a halo, and a divine aura." },
    { value: "Bajoran", label: "Bajoran", prompt: "Transform the character into a Bajoran. Add a crinkled ridge across the bridge of the nose." },
    { value: "Borg", label: "Borg", prompt: "Transform the character into a Borg Drone. Add cybernetic implants, pale skin, and a mechanical eyepiece." },
    { value: "Cardassian", label: "Cardassian", prompt: "Transform the character into a Cardassian. Give them grey skin with distinct neck ridges and spoon-shaped forehead markings." },
    { value: "Centaur", label: "Centaur", prompt: "Transform the character into a Centaur. Keep the human upper body but replace the lower body with that of a horse." },
    { value: "Changeling", label: "Changeling", prompt: "Transform the character into a Changeling. Give them very pale, featureless skin and large dark eyes." },
    { value: "Cyborg", label: "Cyborg", prompt: "Transform the character into a Cyborg. Integrate mechanical parts, metal plating, and glowing lights into their body." },
    { value: "Demon", label: "Demon", prompt: "Transform the character into a Demon. Add horns, leathery wings, red skin, and a sinister aura." },
    { value: "Dragonborn", label: "Dragonborn", prompt: "Transform the character into a Dragonborn. Give them draconic scales and a dragon-like head." },
    { value: "Drow", label: "Drow (Dark Elf)", prompt: "Transform the character into a Drow. Give them dark skin, white hair, and distinct elven features." },
    { value: "Dwarf", label: "Dwarf", prompt: "Transform the character into a Dwarf. Add characteristic features of a Dwarf (stout build, beard if male) while maintaining the original pose and identity." },
    { value: "Elf", label: "Elf", prompt: "Transform the character into an Elf. Add characteristic features of an Elf (pointed ears, elegant features) while maintaining the original pose and identity." },
    { value: "Fairy", label: "Fairy", prompt: "Transform the character into a Fairy. Add insect-like wings (butterfly or dragonfly) and a magical glow." },
    { value: "Ferengi", label: "Ferengi", prompt: "Transform the character into a Ferengi. Give them extremely large ears, sharp teeth, and a wrinkled nose." },
    { value: "Genasi-Air", label: "Genasi (Air)", prompt: "Transform the character into an Air Genasi. Give them pale blue skin and hair that seems to float." },
    { value: "Genasi-Earth", label: "Genasi (Earth)", prompt: "Transform the character into an Earth Genasi. Give them stone-like skin texture and earthy tones." },
    { value: "Genasi-Fire", label: "Genasi (Fire)", prompt: "Transform the character into a Fire Genasi. Give them burning red/orange skin and hair that resembles flames." },
    { value: "Genasi-Water", label: "Genasi (Water)", prompt: "Transform the character into a Water Genasi. Give them blue/green skin and a fluid, aquatic appearance." },
    { value: "Gnome", label: "Gnome", prompt: "Transform the character into a Gnome. Add characteristic features of a Gnome while maintaining the original pose and identity." },
    { value: "Goblin", label: "Goblin", prompt: "Transform the character into a Goblin. Give them green skin, a large nose, and pointy ears." },
    { value: "Gorn", label: "Gorn", prompt: "Transform the character into a Gorn. Give them a full reptilian humanoid appearance with green scales and compound eyes." },
    { value: "Half-Elf", label: "Half-Elf", prompt: "Transform the character into a Half-Elf. Add subtle elven features while maintaining the original pose and identity." },
    { value: "Half-Orc", label: "Half-Orc", prompt: "Transform the character into a Half-Orc. Give them prominent lower teeth, greyish skin, and a strong build." },
    { value: "Halfling", label: "Halfling", prompt: "Transform the character into a Halfling. Add characteristic features of a Halfling while maintaining the original pose and identity." },
    { value: "Hobgoblin", label: "Hobgoblin", prompt: "Transform the character into a Hobgoblin. Give them orange/red skin and a disciplined, martial appearance." },
    { value: "Human", label: "Human", prompt: "Transform the character into a Human. Add characteristic features of a Human while maintaining the original pose and identity." },
    { value: "Kenku", label: "Kenku", prompt: "Transform the character into a Kenku. Give them bird-like features, feathers, and a beak (flightless)." },
    { value: "Klingon", label: "Klingon", prompt: "Transform the character into a Klingon. Add characteristic ridges on the forehead and wild, voluminous hair." },
    { value: "Kobold", label: "Kobold", prompt: "Transform the character into a Kobold. Give them reptilian features, scales, and a small, wiry frame." },
    { value: "Lizardfolk", label: "Lizardfolk", prompt: "Transform the character into Lizardfolk. Give them reptilian scales, a tail, and a lizard head." },
    { value: "Loxodon", label: "Loxodon", prompt: "Transform the character into a Loxodon. Give them elephantine features, including a trunk and leathery skin." },
    { value: "Mermaid", label: "Mermaid", prompt: "Transform the character into a Mermaid. Replace legs with a fish tail and add aquatic features." },
    { value: "Minotaur", label: "Minotaur", prompt: "Transform the character into a Minotaur. Give them a bull's head, horns, and a powerful, furry build." },
    { value: "Orc", label: "Orc", prompt: "Transform the character into an Orc. Give them green/grey skin, tusks, and a muscular build." },
    { value: "Orion", label: "Orion", prompt: "Transform the character into an Orion. Give them vibrant green skin." },
    { value: "Romulan", label: "Romulan", prompt: "Transform the character into a Romulan. Add pointed ears and a V-shaped forehead ridge." },
    { value: "Satyr", label: "Satyr", prompt: "Transform the character into a Satyr. Give them goat legs, hooves, and small horns." },
    { value: "Skeleton", label: "Skeleton", prompt: "Transform the character into a Skeleton. Remove all flesh, leaving only clean bone structure, perhaps wearing the original clothes." },
    { value: "Tabaxi", label: "Tabaxi", prompt: "Transform the character into a Tabaxi. Give them feline features, fur, and a cat-like tail." },
    { value: "Tiefling", label: "Tiefling", prompt: "Transform the character into a Tiefling. Add horns, a tail, and possibly unusual skin color." },
    { value: "Trill", label: "Trill", prompt: "Transform the character into a Trill. Add a pattern of dark spots running down the sides of their face and neck." },
    { value: "Triton", label: "Triton", prompt: "Transform the character into a Triton. Give them aquatic features, webbed fingers, and fins." },
    { value: "Vampire", label: "Vampire", prompt: "Transform the character into a Vampire. Give them pale skin, fangs, and a gothic, aristocratic demeanor." },
    { value: "Vulcan", label: "Vulcan", prompt: "Transform the character into a Vulcan. Add characteristic pointed ears and straight eyebrows." },
    { value: "Warforged", label: "Warforged", prompt: "Transform the character into a Warforged. Give them a body made of wood, stone, and metal, appearing as a living construct." },
    { value: "Werewolf", label: "Werewolf", prompt: "Transform the character into a Werewolf (hybrid form). Give them fur, a wolf-like snout, and claws." },
    { value: "Zombie", label: "Zombie", prompt: "Transform the character into a Zombie. Give them decaying skin, sunken eyes, and a tattered appearance." }
  ]),
  
  genders: sortOpts([
     { value: "Original", label: "As Is / Original", prompt: "" },
     { value: "Female", label: "Female", prompt: "Transform the character to appear Female. Adjust physical features to be typically feminine while preserving the character's identity." },
     { value: "Intersex", label: "Intersex", prompt: "Transform the character to appear Androgynous/Intersex. Blend masculine and feminine features for a non-binary appearance." },
     { value: "Male", label: "Male", prompt: "Transform the character to appear Male. Adjust physical features to be typically masculine while preserving the character's identity." },
  ]),

  ageGroups: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Adult", label: "Adult", prompt: "Modify the character's apparent age to be an Adult." },
    { value: "Elderly", label: "Elderly", prompt: "Modify the character's apparent age to be Elderly." },
    { value: "Middle-Aged", label: "Middle-Aged", prompt: "Modify the character's apparent age to be Middle-Aged." },
    { value: "Preteen", label: "Preteen", prompt: "Modify the character's apparent age to be a Preteen." },
    { value: "Teenager", label: "Teenager", prompt: "Modify the character's apparent age to be a Teenager." },
    { value: "Young Adult", label: "Young Adult", prompt: "Modify the character's apparent age to be a Young Adult." },
  ]),

  hairColors: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Auburn", label: "Auburn", prompt: "Change the hair color to Auburn." },
    { value: "Bald", label: "Bald", prompt: "Remove the hair completely. Render a realistic bald head." },
    { value: "Black", label: "Black", prompt: "Change the hair color to Black." },
    { value: "Blonde", label: "Blonde", prompt: "Change the hair color to Blonde." },
    { value: "Blue", label: "Blue", prompt: "Change the hair color to Blue." },
    { value: "Brown", label: "Brown", prompt: "Change the hair color to Brown." },
    { value: "Gold", label: "Gold", prompt: "Change the hair color to metallic Gold." },
    { value: "Green", label: "Green", prompt: "Change the hair color to Green." },
    { value: "Grey", label: "Grey", prompt: "Change the hair color to Grey." },
    { value: "Multicolor", label: "Multicolor", prompt: "Change the hair color to Rainbow/Multicolor." },
    { value: "Orange", label: "Orange", prompt: "Change the hair color to Orange." },
    { value: "Pink", label: "Pink", prompt: "Change the hair color to Pink." },
    { value: "Purple", label: "Purple", prompt: "Change the hair color to Purple." },
    { value: "Red", label: "Red / Ginger", prompt: "Change the hair color to Red / Ginger." },
    { value: "Silver", label: "Silver", prompt: "Change the hair color to metallic Silver." },
    { value: "Teal", label: "Teal", prompt: "Change the hair color to Teal." },
    { value: "White", label: "White", prompt: "Change the hair color to White." },
  ]),

  eyeColors: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Amber", label: "Amber", prompt: "Change the eye color to Amber." },
    { value: "Black", label: "Black", prompt: "Change the eye color to deep Black." },
    { value: "Blue", label: "Blue", prompt: "Change the eye color to bright Blue." },
    { value: "Brown", label: "Brown", prompt: "Change the eye color to dark Brown." },
    { value: "Green", label: "Green", prompt: "Change the eye color to Emerald Green." },
    { value: "Grey", label: "Grey", prompt: "Change the eye color to Grey." },
    { value: "Hazel", label: "Hazel", prompt: "Change the eye color to Hazel." },
    { value: "Glowing Blue", label: "Glowing Blue", prompt: "Make the eyes glow Blue." },
    { value: "Glowing Red", label: "Glowing Red", prompt: "Make the eyes glow Red." },
    { value: "Glowing White", label: "Glowing White", prompt: "Make the eyes glow White." },
    { value: "Heterochromia", label: "Heterochromia", prompt: "Give the character Heterochromia (one blue eye, one green eye)." },
    { value: "Purple", label: "Purple", prompt: "Change the eye color to Purple/Violet." },
    { value: "Red", label: "Red", prompt: "Change the eye color to Red." },
    { value: "Silver", label: "Silver", prompt: "Change the eye color to Silver." },
    { value: "Yellow", label: "Yellow", prompt: "Change the eye color to Yellow." },
  ]),

  skinTones: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Asian", label: "Asian / East Asian", prompt: "Change skin tone to East Asian ethnicity." },
    { value: "Black", label: "Black / Deep Dark", prompt: "Change skin tone to Deep Black." },
    { value: "Blue", label: "Blue (Fantasy)", prompt: "Change skin tone to Blue (Alien)." },
    { value: "Brown", label: "Brown", prompt: "Change skin tone to Brown." },
    { value: "DarkBrown", label: "Dark Brown", prompt: "Change skin tone to Dark Brown." },
    { value: "Fair", label: "Fair", prompt: "Change skin tone to Fair." },
    { value: "Green", label: "Green (Fantasy)", prompt: "Change skin tone to Green (Alien)." },
    { value: "Hispanic", label: "Hispanic / Latino", prompt: "Change skin tone to Hispanic / Latino ethnicity." },
    { value: "Indigenous", label: "Indigenous / Native", prompt: "Change skin tone to Indigenous / Native American ethnicity." },
    { value: "Medium", label: "Medium / Beige", prompt: "Change skin tone to Medium / Beige." },
    { value: "Metallic", label: "Metallic", prompt: "Change skin to appear Metallic or Robotic." },
    { value: "MiddleEastern", label: "Middle Eastern", prompt: "Change skin tone to Middle Eastern ethnicity." },
    { value: "Olive", label: "Olive", prompt: "Change skin tone to Olive." },
    { value: "Pale", label: "Pale / Porcelain", prompt: "Change skin tone to Pale / Porcelain." },
    { value: "Red", label: "Red (Fantasy)", prompt: "Change skin tone to Red (Alien)." },
    { value: "SouthAsian", label: "South Asian", prompt: "Change skin tone to South Asian ethnicity." },
    { value: "Tan", label: "Tan / Bronze", prompt: "Change skin tone to Tan / Bronze." },
  ]),

  bodyMods: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Birthmark", label: "Birthmark (Face)", prompt: "Add a distinctive birthmark on the face." },
    { value: "CyborgParts", label: "Cyborg Implants", prompt: "Add visible cybernetic implants and panel lines to the skin." },
    { value: "Freckles", label: "Freckles", prompt: "Add a dusting of freckles across the nose and cheeks." },
    { value: "GoldSkin", label: "Gold Leaf Skin", prompt: "Add patches of gold leaf texture to the skin." },
    { value: "Piercings", label: "Piercings (Face)", prompt: "Add tasteful facial piercings (nose ring, eyebrow ring, lip ring)." },
    { value: "Scales", label: "Scales (Patches)", prompt: "Add patches of reptilian scales on the skin." },
    { value: "ScarEye", label: "Scar (Over Eye)", prompt: "Add a cool scar running vertically over one eye." },
    { value: "ScarCheek", label: "Scar (Cheek)", prompt: "Add a small scar on the cheek." },
    { value: "TattooArm", label: "Tattoo (Sleeve)", prompt: "Add intricate sleeve tattoos on the arms." },
    { value: "TattooFace", label: "Tattoo (Face)", prompt: "Add tribal or artistic tattoos on the face." },
    { value: "TattooNeck", label: "Tattoo (Neck)", prompt: "Add a tattoo on the neck." },
    { value: "Vitiligo", label: "Vitiligo", prompt: "Add vitiligo patterns to the skin." },
    { value: "WarPaint", label: "War Paint", prompt: "Add warrior face paint." },
  ]),

  clothing: sortOpts([
    { value: "as-is", label: "As Is (Default)", prompt: "" },
    { value: "less", label: "Fewer Clothes", prompt: "Reduce the amount of clothing to be lighter, such as summer wear or swimwear. Do not generate explicit pornography." },
    { value: "more", label: "More Clothing", prompt: "Add more layers of clothing. Ensure the character is well-covered and dressed warmly." },
    { value: "nude", label: "Nude (Implied)", prompt: "Minimize clothing to the absolute limit to imply nudity without explicit genitalia. Focus on artistic anatomy." },
  ]),

  footwear: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Anklets", label: "Anklets", prompt: "Ensure the character is barefoot but wearing decorative anklets." },
    { value: "Barefoot", label: "Barefoot", prompt: "Ensure the character is completely barefoot." },
    { value: "Boots", label: "Boots", prompt: "Ensure the character is wearing Boots." },
    { value: "Clogs", label: "Clogs", prompt: "Ensure the character is wearing Clogs." },
    { value: "Leather Wraps", label: "Leather Wraps", prompt: "Ensure the character is wearing Leather Wraps on their feet." },
    { value: "Sandals", label: "Sandals", prompt: "Ensure the character is wearing Sandals." },
    { value: "Shoes", label: "Shoes", prompt: "Ensure the character is wearing Shoes." },
    { value: "Sneakers", label: "Sneakers", prompt: "Ensure the character is wearing Sneakers." },
  ]),

  items: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Axe", label: "Axe", prompt: "The character is wielding a large battle axe." },
    { value: "Book", label: "Book/Grimoire", prompt: "The character is holding an ancient book or grimoire." },
    { value: "Bow", label: "Bow & Arrow", prompt: "The character is holding a bow." },
    { value: "Camera", label: "Camera", prompt: "The character is holding a camera." },
    { value: "Dagger", label: "Dagger", prompt: "The character is holding a dagger." },
    { value: "Flower", label: "Flower", prompt: "The character is holding a beautiful flower." },
    { value: "Gun", label: "Gun/Pistol", prompt: "The character is holding a futuristic pistol." },
    { value: "Lantern", label: "Lantern", prompt: "The character is holding a glowing lantern." },
    { value: "Laptop", label: "Laptop", prompt: "The character is holding a laptop." },
    { value: "Lightsaber", label: "Lightsaber", prompt: "The character is holding a lightsaber." },
    { value: "Lute", label: "Lute/Instrument", prompt: "The character is holding a lute." },
    { value: "Orb", label: "Magic Orb", prompt: "The character is holding a glowing magic orb." },
    { value: "Phone", label: "Smartphone", prompt: "The character is holding a smartphone." },
    { value: "Potion", label: "Potion", prompt: "The character is holding a glass potion bottle." },
    { value: "Scroll", label: "Scroll", prompt: "The character is holding a parchment scroll." },
    { value: "Shield", label: "Shield", prompt: "The character is holding a shield." },
    { value: "Staff", label: "Staff", prompt: "The character is holding a magical staff." },
    { value: "Sword", label: "Sword", prompt: "The character is wielding a sword." },
    { value: "Tea", label: "Tea Cup", prompt: "The character is holding a cup of tea." },
    { value: "Torch", label: "Torch", prompt: "The character is holding a burning torch." },
    { value: "Wand", label: "Wand", prompt: "The character is holding a magic wand." },
  ]),

  creatures: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Bird", label: "Bird (Shoulder)", prompt: "Add a small bird perched on the character's shoulder." },
    { value: "Cat", label: "Cat", prompt: "Add a cat sitting next to the character." },
    { value: "Dinosaur", label: "Dinosaur (Small)", prompt: "Add a small pet dinosaur next to the character." },
    { value: "Dog", label: "Dog", prompt: "Add a loyal dog sitting next to the character." },
    { value: "Dragon", label: "Dragon (Small)", prompt: "Add a small shoulder dragon." },
    { value: "Fairy", label: "Fairy", prompt: "Add a glowing fairy hovering near the character." },
    { value: "Fox", label: "Fox", prompt: "Add a fox sitting near the character." },
    { value: "Ghost", label: "Ghost", prompt: "Add a cute ghost floating nearby." },
    { value: "Griffin", label: "Griffin (Pet)", prompt: "Add a small baby griffin nearby." },
    { value: "Owl", label: "Owl", prompt: "Add an owl perched nearby." },
    { value: "Phoenix", label: "Phoenix", prompt: "Add a fiery phoenix nearby." },
    { value: "Rabbit", label: "Rabbit", prompt: "Add a rabbit nearby." },
    { value: "Raven", label: "Raven", prompt: "Add a raven nearby." },
    { value: "Robot", label: "Robot Pet", prompt: "Add a small floating robot companion." },
    { value: "Slime", label: "Slime", prompt: "Add a cute slime creature nearby." },
    { value: "Wolf", label: "Wolf", prompt: "Add a large wolf companion standing guard." },
  ]),

  backgrounds: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Arabian", label: "Arabian Palace", prompt: "Replace the background with an Arabian Palace, featuring mosaics, arches, and silk curtains." },
    { value: "Aztec", label: "Aztec Temple", prompt: "Replace the background with an Aztec Temple, featuring stone pyramids and jungle overgrowth." },
    { value: "Beach", label: "Beach", prompt: "Replace the background with a realistic Beach. Ensure lighting and reflections match." },
    { value: "BioForest", label: "Bioluminescent Forest", prompt: "Replace the background with a Bioluminescent Forest, with glowing plants and night-time lighting." },
    { value: "Castle", label: "Castle", prompt: "Replace the background with a Castle." },
    { value: "Chinese", label: "Chinese Garden", prompt: "Replace the background with a Chinese Garden, featuring pagodas, ponds, and cherry blossoms." },
    { value: "City", label: "City", prompt: "Replace the background with a modern City." },
    { value: "CyberpunkSlums", label: "Cyberpunk Slums", prompt: "Replace the background with Cyberpunk Slums, featuring neon signs, rain, and high-tech decay." },
    { value: "Desert", label: "Desert", prompt: "Replace the background with a realistic Desert. Ensure lighting and shadows match." },
    { value: "Diner", label: "Diner (1950s)", prompt: "Replace the background with a 1950s Diner, featuring neon signs, checkerboard floors, and chrome." },
    { value: "Dojo", label: "Dojo (Japanese)", prompt: "Replace the background with a traditional Japanese Dojo, with tatami mats and wooden architecture." },
    { value: "Egypt", label: "Egypt Pyramids", prompt: "Replace the background with Ancient Egyptian Pyramids and desert sands." },
    { value: "Forest", label: "Forest", prompt: "Replace the background with a realistic Forest. Ensure lighting and shadows match." },
    { value: "Gothic", label: "Gothic Cathedral", prompt: "Replace the background with a Gothic Cathedral, featuring stained glass, stone arches, and candles." },
    { value: "Greek", label: "Greek Acropolis", prompt: "Replace the background with the Greek Acropolis, featuring white marble temples under a blue sky." },
    { value: "Ice Cave", label: "Ice Cave", prompt: "Replace the background with an Ice Cave, featuring blue translucent ice and cold lighting." },
    { value: "Jungle", label: "Jungle", prompt: "Replace the background with a dense Jungle." },
    { value: "Laboratory", label: "Laboratory", prompt: "Replace the background with a Laboratory." },
    { value: "Library", label: "Library", prompt: "Replace the background with a Library." },
    { value: "Mars", label: "Mars", prompt: "Replace the background with the surface of Mars." },
    { value: "Moon", label: "Moon", prompt: "Replace the background with the Moon surface." },
    { value: "Mountains", label: "Mountains", prompt: "Replace the background with majestic Mountains." },
    { value: "Plains", label: "Plains", prompt: "Replace the background with realistic Plains. Ensure lighting and shadows match." },
    { value: "Rivers", label: "Rivers", prompt: "Replace the background with a River. Ensure lighting and reflections match." },
    { value: "Roman", label: "Roman Forum", prompt: "Replace the background with the Roman Forum, featuring marble columns and classical statues." },
    { value: "Saloon", label: "Saloon (Wild West)", prompt: "Replace the background with a Wild West Saloon, featuring wooden floors and swinging doors." },
    { value: "Sci-Fi", label: "Sci-Fi Interior", prompt: "Replace the background with a clean Sci-Fi spaceship interior." },
    { value: "Sea", label: "Sea", prompt: "Replace the background with the Sea. Ensure lighting and reflections match." },
    { value: "SkyCastle", label: "Sky Castle", prompt: "Replace the background with a Castle floating in the sky among clouds." },
    { value: "Snow", label: "Snow", prompt: "Replace the background with a Snowy landscape. Ensure lighting and shadows match." },
    { value: "Spaceship", label: "Spaceship", prompt: "Replace the background with a Spaceship interior." },
    { value: "SteampunkCity", label: "Steampunk City", prompt: "Replace the background with a Steampunk City, filled with brass gears, steam, and brick." },
    { value: "Transparent", label: "Transparent", prompt: "Remove the existing background completely and replace it with a transparent alpha channel. Ensure the output is a RGBA PNG with transparency." },
    { value: "UnderwaterCity", label: "Underwater City", prompt: "Replace the background with an Underwater City, protected by a glass dome." },
    { value: "Victorian", label: "Victorian Street", prompt: "Replace the background with a foggy Victorian Street, featuring cobblestones and gas lamps." },
    { value: "Viking", label: "Viking Longhall", prompt: "Replace the background with a Viking Longhall, featuring wooden beams, fire pits, and shields." },
    { value: "Village", label: "Village", prompt: "Replace the background with a Village." },
    { value: "Volcanic", label: "Volcanic Crater", prompt: "Replace the background with a Volcanic Crater, featuring lava and dark rock." },
  ]),

  timeOfDay: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Afternoon", label: "Afternoon", prompt: "Change the lighting and atmosphere to depict Afternoon." },
    { value: "BlueHour", label: "Blue Hour / Twilight", prompt: "Change the lighting and atmosphere to Blue Hour. Use cool, soft, ambient light just after sunset." },
    { value: "Evening", label: "Evening", prompt: "Change the lighting and atmosphere to Evening." },
    { value: "GoldenHour", label: "Golden Hour", prompt: "Change the lighting and atmosphere to Golden Hour. Use warm, golden, directional light." },
    { value: "Midnight", label: "Midnight", prompt: "Change the lighting and atmosphere to Midnight. Use deep blacks and silvery moonlight." },
    { value: "Morning", label: "Morning", prompt: "Change the lighting and atmosphere to depict a bright, clear Morning." },
    { value: "Night", label: "Night", prompt: "Change the lighting and atmosphere to Night. Use dark tones and moonlit highlights." },
    { value: "Noon", label: "Noon", prompt: "Change the lighting and atmosphere to depict High Noon. Use bright, direct, overhead sunlight." },
    { value: "Sunrise", label: "Sunrise", prompt: "Change the lighting and atmosphere to depict Sunrise. Use soft, warm, low-angle light." },
    { value: "Sunset", label: "Sunset", prompt: "Change the lighting and atmosphere to depict Sunset. Use vibrant oranges, purples, and dramatic shadows." },
  ]),

  weather: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Clear", label: "Clear / Sunny", prompt: "Make the weather clear and sunny." },
    { value: "Cloudy", label: "Cloudy", prompt: "Make the weather overcast and cloudy." },
    { value: "Foggy", label: "Foggy", prompt: "Add thick fog and mist to the scene." },
    { value: "Rain", label: "Rainy", prompt: "Make it rain. Add wet surfaces and falling rain drops." },
    { value: "Snowing", label: "Snowing", prompt: "Make it snow. Add falling snowflakes and cold atmosphere." },
    { value: "Storm", label: "Stormy", prompt: "Make the weather stormy with dark clouds and lightning." },
    { value: "Windy", label: "Windy", prompt: "Make it look windy, with blowing hair and clothes." },
  ]),

  lighting: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Cinematic", label: "Cinematic", prompt: "Use cinematic lighting with high contrast and dramatic shadows." },
    { value: "Cyberpunk", label: "Cyberpunk / Neon", prompt: "Use neon pink and blue lighting." },
    { value: "Dark", label: "Dark / Low Key", prompt: "Use low-key lighting with deep shadows." },
    { value: "Flat", label: "Flat / Soft", prompt: "Use soft, even lighting with minimal shadows." },
    { value: "Natural", label: "Natural", prompt: "Use realistic natural lighting." },
    { value: "Rembrandt", label: "Rembrandt", prompt: "Use classic Rembrandt lighting." },
    { value: "Studio", label: "Studio", prompt: "Use perfect studio lighting." },
    { value: "Volumetric", label: "Volumetric / God Rays", prompt: "Add volumetric fog and god rays." },
  ]),

  moods: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Angry", label: "Angry / Aggressive", prompt: "Make the mood angry and aggressive." },
    { value: "Calm", label: "Calm / Peaceful", prompt: "Make the mood calm and peaceful." },
    { value: "Creepy", label: "Creepy / Horror", prompt: "Make the mood creepy and unsettling." },
    { value: "Epic", label: "Epic / Heroic", prompt: "Make the mood epic and heroic." },
    { value: "Happy", label: "Happy / Joyful", prompt: "Make the mood happy and joyful." },
    { value: "Melancholic", label: "Melancholic / Sad", prompt: "Make the mood melancholic and sad." },
    { value: "Mysterious", label: "Mysterious", prompt: "Make the mood mysterious." },
    { value: "Romantic", label: "Romantic", prompt: "Make the mood romantic." },
  ]),

  techLevels: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "Ancient", label: "Ancient", prompt: "Transform the setting to an Ancient era (Rome/Greece)." },
    { value: "Cyberpunk", label: "Cyberpunk", prompt: "Transform the setting to a Cyberpunk Near Future." },
    { value: "Far Future", label: "Far Future", prompt: "Transform the setting to the Far Future." },
    { value: "Industrial", label: "Industrial / Steampunk", prompt: "Transform the setting to the Industrial/Steampunk era." },
    { value: "Medieval", label: "Medieval", prompt: "Transform the setting to the Medieval period." },
    { value: "Modern", label: "Modern", prompt: "Transform the setting to the Modern day." },
    { value: "Primitive", label: "Primitive", prompt: "Transform the setting to a primitive, stone-age level." },
    { value: "Renaissance", label: "Renaissance", prompt: "Transform the setting to the Renaissance period." },
    { value: "Sci-Fi", label: "Sci-Fi", prompt: "Transform the setting to a clean Sci-Fi Future." },
  ]),

  cameraAngles: sortOpts([
    { value: "Original", label: "As Is / Original", prompt: "" },
    { value: "CloseUp", label: "Close Up", prompt: "Frame the shot as a Close Up on the face." },
    { value: "EyeLevel", label: "Eye Level", prompt: "Frame the shot at Eye Level." },
    { value: "Fisheye", label: "Fisheye Lens", prompt: "Use a Fisheye lens effect." },
    { value: "FullBody", label: "Full Body", prompt: "Frame the shot to show the Full Body." },
    { value: "LowAngle", label: "Low Angle", prompt: "Shoot from a Low Angle looking up." },
    { value: "Macro", label: "Macro", prompt: "Use a Macro lens for extreme detail." },
    { value: "Overhead", label: "Overhead / Bird's Eye", prompt: "Shoot from directly overhead." },
    { value: "Portrait", label: "Portrait Lens (85mm)", prompt: "Use an 85mm Portrait lens with bokeh background." },
    { value: "WideAngle", label: "Wide Angle", prompt: "Use a Wide Angle lens." },
  ]),

  aspectRatios: sortOpts([
    { value: "1:1", label: "1:1 (Square)", prompt: "Generate image with 1:1 aspect ratio." },
    { value: "16:9", label: "16:9 (Landscape)", prompt: "Generate image with 16:9 aspect ratio." },
    { value: "9:16", label: "9:16 (Portrait)", prompt: "Generate image with 9:16 aspect ratio." },
    { value: "4:3", label: "4:3 (Photo)", prompt: "Generate image with 4:3 aspect ratio." },
    { value: "3:4", label: "3:4 (Portrait Photo)", prompt: "Generate image with 3:4 aspect ratio." },
  ]),
};
